function out1 = legInvKin(L1,L2,x,y)
%legInvKin
%    OUT1 = legInvKin(L1,L2,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    03-Oct-2023 19:54:55

t2 = L1.^2;
t3 = L2.^2;
t4 = x.^2;
t5 = y.^2;
t6 = L1.*x.*2.0;
t7 = L1.*y.*2.0;
t8 = L1.*L2.*2.0;
t9 = -t7;
t10 = -t2;
t11 = -t3;
t12 = -t4;
t13 = -t5;
t14 = t2+t4+t5+t9+t11;
t15 = t4+t5+t8+t10+t11;
t16 = t2+t3+t8+t12+t13;
t17 = 1.0./t14;
t18 = 1.0./t15;
t19 = t15.*t16;
t20 = sqrt(t19);
t21 = t18.*t20;
t22 = atan(t21);
t23 = t8.*t21;
t24 = t2.*t21;
t25 = t3.*t21;
t27 = t4.*t21;
t28 = t5.*t21;
t26 = t22.*2.0;
out1 = reshape([atan(t17.*(t6+t23+t27+t28+t10.*t21+t11.*t21)).*2.0,atan(t17.*(t6+t24+t25+t12.*t21+t13.*t21-L1.*L2.*t21.*2.0)).*2.0,-t26,t26],[2,2]);
end
